---

- hosts: webserver
  remote_user: root
  vars:
    nginx_port: "80"
    nginx_name: "www.baidu.com"
    new_password: "YanzeRen..971019"
  tasks:
    - name: 传输源文件
      template:
        src: ./lnmp.repo
        dest: /etc/yum.repos.d/lnmp.repo

    - name: 下载相关软件
      yum:
        name: ['nginx', 'mysql-community-server', 'php', 'php-fpm', 'php-mysql', 'php-devel', 'php-mbstring', 'php-mcrypt', 'php-gd', 'php-xml']
        state: latest

    - name: 传输nginx配置文件
      template:
        src: ./nginx.conf
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - 重新启动Nginx服务

    - name: MySQL初始化文件传入
      template:
        src: ./mysql.sh
        dest: /root/mysql.sh

    - name: MySQL初始化进行中... ... ...
      shell: "bash /root/mysql.sh"

    - name: 启动php服务
      service: name=php-fpm state=started enabled=true

  handlers:
    - name: 重新启动Nginx服务
      service: name=nginx state=restarted enabled=true    
